/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 CubeSatRender.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CubeSatRender.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.CubeSatModel_1.geometry} material={materials.satin_finish_aluminum} />
        <mesh geometry={nodes.CubeSatModel_2.geometry} material={materials.color} />
        <mesh geometry={nodes.CubeSatModel_3.geometry} material={materials['color-2']} />
        <mesh geometry={nodes.CubeSatModel_4.geometry} material={materials['color-4']} />
        <mesh geometry={nodes.CubeSatModel_5.geometry} material={materials['color-5']} />
        <mesh geometry={nodes.CubeSatModel_6.geometry} material={materials['color-6']} />
        <mesh geometry={nodes.CubeSatModel_7.geometry} material={materials['color-8']} />
        <mesh geometry={nodes.CubeSatModel_8.geometry} material={materials['color-9']} />
        <mesh geometry={nodes.CubeSatModel_9.geometry} material={materials['color-10']} />
        <mesh geometry={nodes.CubeSatModel_10.geometry} material={materials['color-12']} />
        <mesh geometry={nodes.CubeSatModel_11.geometry} material={materials['color-18']} />
        <mesh geometry={nodes.CubeSatModel_12.geometry} material={materials['color-19']} />
        <mesh geometry={nodes.CubeSatModel_13.geometry} material={materials['color-21']} />
        <mesh geometry={nodes.CubeSatModel_14.geometry} material={materials['color-22']} />
        <mesh geometry={nodes.CubeSatModel_15.geometry} material={materials['color-23']} />
        <mesh geometry={nodes.CubeSatModel_16.geometry} material={materials['color-24']} />
        <mesh geometry={nodes.CubeSatModel_17.geometry} material={materials['color-25']} />
        <mesh geometry={nodes.CubeSatModel_18.geometry} material={materials['color-26']} />
        <mesh geometry={nodes.CubeSatModel_19.geometry} material={materials['color-29']} />
        <mesh geometry={nodes.CubeSatModel_20.geometry} material={materials['color-31']} />
        <mesh geometry={nodes.CubeSatModel_21.geometry} material={materials['color-32']} />
        <mesh geometry={nodes.CubeSatModel_22.geometry} material={materials['color-33']} />
        <mesh geometry={nodes.CubeSatModel_23.geometry} material={materials['color-34']} />
        <mesh geometry={nodes.CubeSatModel_24.geometry} material={materials['color-36']} />
        <mesh geometry={nodes.CubeSatModel_25.geometry} material={materials['color-37']} />
        <mesh geometry={nodes.CubeSatModel_26.geometry} material={materials['color-39']} />
        <mesh geometry={nodes.CubeSatModel_27.geometry} material={materials['color-40']} />
        <mesh geometry={nodes.CubeSatModel_28.geometry} material={materials['color-42']} />
        <mesh geometry={nodes.CubeSatModel_29.geometry} material={materials['color-44']} />
        <mesh geometry={nodes.CubeSatModel_30.geometry} material={materials.polished_copper} />
        <mesh geometry={nodes.CubeSatModel_31.geometry} material={materials['color-47']} />
        <mesh geometry={nodes.CubeSatModel_32.geometry} material={materials.carbon_steel} />
        <mesh geometry={nodes.CubeSatModel_33.geometry} material={materials['color-48']} />
        <mesh geometry={nodes.CubeSatModel_34.geometry} material={materials['color-49']} />
        <mesh geometry={nodes.CubeSatModel_35.geometry} material={materials.polished_brass} />
        <mesh geometry={nodes.CubeSatModel_36.geometry} material={materials['color-50']} />
        <mesh geometry={nodes.CubeSatModel_37.geometry} material={materials['color-51']} />
        <mesh geometry={nodes.CubeSatModel_38.geometry} material={materials['color-50_(Cosmetic_Thread)']} />
        <mesh geometry={nodes.CubeSatModel_39.geometry} material={materials['color-52']} />
        <mesh geometry={nodes.CubeSatModel_40.geometry} material={materials['carbon_steel-2']} />
        <mesh geometry={nodes.CubeSatModel_41.geometry} material={materials.light_grey_low_gloss_plastic} />
        <mesh geometry={nodes.CubeSatModel_42.geometry} material={materials['color-54']} />
        <mesh geometry={nodes.CubeSatModel_43.geometry} material={materials['color-55']} />
        <mesh geometry={nodes.CubeSatModel_44.geometry} material={materials['color-56']} />
        <mesh geometry={nodes.CubeSatModel_45.geometry} material={materials['color-57']} />
        <mesh geometry={nodes.CubeSatModel_46.geometry} material={materials['color-58']} />
        <mesh geometry={nodes.CubeSatModel_47.geometry} material={materials['color-61']} />
      </group>
    </group>
  )
}

useGLTF.preload('/CubeSatRender.glb')
